### ISSUE TITLE
please help me to install it

### ISSUE THREAD

**Issue by chnbohwr** [grnadav/SaveToPhotoAlbumPhonegapPlugin#1]
hi i try to install this plugin by 'cordova plugin add' command

but it doesn't work

please help me to install your plugin !!

**Comment by luhcas** [comment]
Hi Nadav,
can you please help me to install the plugin?
When creating a new cordova project, where do i have to copy which folder from the SaveToPhotoAlbumPhonegapPlugin?

I have tried many ways but i there is always an error "Could not find plugin info in...".

Thank you very much!

**Comment by grnadav** [comment]
Hey
Well, this plugin is WAAAAY out of date and no longer installable in the current Phonegap plugin architecture.
I guess you could build a new plugin using the native code (which I guess is still relevant).
Anyway, if you do that, a PR would be hugely appreciated.
