### ISSUE TITLE
Kindly Please Update this Plugin

### ISSUE THREAD

**Issue by daksamedia** [grnadav/SaveToPhotoAlbumPhonegapPlugin#2]
Hello @grnadav, 
Your plugin may be useful, I tried to implement but I didn't get success. 
Kindly please update this plugin, I really appreaciate if you update it later.

Thanks in advance.

**Comment by grnadav** [comment]
Hi,
this plugin is very very out-dated. 
as i do not have time to update it, I am locking this repo for comments and leaving it for future reference only.

Thanks and good luck
